"""Create the authoritative 100-case manifest with standard and epistemic gold labels.
"""
import json
import os
import sys

MANIFEST = [
    # ── CATEGORY A: CLEAR POSITIVE / ESTABLISHED THERAPEUTIC (01-20) ──
    {
        "case_id": "TC-001",
        "drug": "Lisinopril",
        "disease": "Hypertension",
        "category": "Category A: Clear positive",
        "gold_label": "established/approved",
        "standard_gold": "SUPPORT",
        "epistemic_gold": "SUPPORT",
        "gold_source": "FDA Approved Drug Label (NDA 019777)",
        "previously_evaluated": True,
        "previous_benchmark_source": "25-case regression (CYN-003)",
        "special_stress_condition": "Canonical ACE inhibitor positive control",
    },
    {
        "case_id": "TC-002",
        "drug": "Aspirin",
        "disease": "Secondary cardiovascular prevention",
        "category": "Category A: Clear positive",
        "gold_label": "established/approved",
        "standard_gold": "SUPPORT",
        "epistemic_gold": "SUPPORT",
        "gold_source": "FDA Approved Indication / AHA/ACC Guidelines",
        "previously_evaluated": True,
        "previous_benchmark_source": "25-case regression (CYN-013)",
        "special_stress_condition": "Established antiplatelet positive control",
    },
    {
        "case_id": "TC-003",
        "drug": "Budesonide",
        "disease": "Asthma",
        "category": "Category A: Clear positive",
        "gold_label": "established/approved",
        "standard_gold": "SUPPORT",
        "epistemic_gold": "SUPPORT",
        "gold_source": "FDA Approved Drug Label (Pulmicort)",
        "previously_evaluated": True,
        "previous_benchmark_source": "25-case regression (CYN-023)",
        "special_stress_condition": "Inhaled corticosteroid positive control",
    },
    {
        "case_id": "TC-004",
        "drug": "Fluticasone",
        "disease": "Allergic rhinitis",
        "category": "Category A: Clear positive",
        "gold_label": "established/approved",
        "standard_gold": "SUPPORT",
        "epistemic_gold": "SUPPORT",
        "gold_source": "FDA Approved Drug Label (Flonase)",
        "previously_evaluated": True,
        "previous_benchmark_source": "25-case regression (CYN-026)",
        "special_stress_condition": "Nasal corticosteroid positive control",
    },
    {
        "case_id": "TC-005",
        "drug": "Trastuzumab",
        "disease": "HER2-positive breast cancer",
        "category": "Category A: Clear positive",
        "gold_label": "established/approved",
        "standard_gold": "SUPPORT",
        "epistemic_gold": "SUPPORT",
        "gold_source": "FDA Approved Drug Label (Herceptin)",
        "previously_evaluated": True,
        "previous_benchmark_source": "25-case regression (CYN-044)",
        "special_stress_condition": "Subtype-specific biomarker oncological therapy",
    },
    {
        "case_id": "TC-006",
        "drug": "Tamoxifen",
        "disease": "ER-positive breast cancer",
        "category": "Category A: Clear positive",
        "gold_label": "established/approved",
        "standard_gold": "SUPPORT",
        "epistemic_gold": "SUPPORT",
        "gold_source": "FDA Approved Drug Label (Nolvadex)",
        "previously_evaluated": True,
        "previous_benchmark_source": "25-case regression (CYN-041)",
        "special_stress_condition": "Subtype-specific SERM indication matching",
    },
    {
        "case_id": "TC-007",
        "drug": "Metformin",
        "disease": "Type 2 diabetes",
        "category": "Category A: Clear positive",
        "gold_label": "established/approved",
        "standard_gold": "SUPPORT",
        "epistemic_gold": "SUPPORT",
        "gold_source": "FDA Approved Drug Label (Glucophage)",
        "previously_evaluated": True,
        "previous_benchmark_source": "30-case holdout (H-001)",
        "special_stress_condition": "First-line metabolic positive control",
    },
    {
        "case_id": "TC-008",
        "drug": "Atorvastatin",
        "disease": "Hypercholesterolemia",
        "category": "Category A: Clear positive",
        "gold_label": "established/approved",
        "standard_gold": "SUPPORT",
        "epistemic_gold": "SUPPORT",
        "gold_source": "FDA Approved Drug Label (Lipitor)",
        "previously_evaluated": False,
        "previous_benchmark_source": "New (V1 benchmark positive)",
        "special_stress_condition": "HMG-CoA reductase inhibitor positive control",
    },
    {
        "case_id": "TC-009",
        "drug": "Levothyroxine",
        "disease": "Hypothyroidism",
        "category": "Category A: Clear positive",
        "gold_label": "established/approved",
        "standard_gold": "SUPPORT",
        "epistemic_gold": "SUPPORT",
        "gold_source": "FDA Approved Drug Label (Synthroid)",
        "previously_evaluated": False,
        "previous_benchmark_source": "New",
        "special_stress_condition": "Endocrine hormone replacement therapy",
    },
    {
        "case_id": "TC-010",
        "drug": "Amoxicillin",
        "disease": "Bacterial infection",
        "category": "Category A: Clear positive",
        "gold_label": "established/approved",
        "standard_gold": "SUPPORT",
        "epistemic_gold": "SUPPORT",
        "gold_source": "FDA Approved Drug Label (Amoxil)",
        "previously_evaluated": False,
        "previous_benchmark_source": "New",
        "special_stress_condition": "Broad spectrum antibacterial",
    },
    {
        "case_id": "TC-011",
        "drug": "Amlodipine",
        "disease": "Hypertension",
        "category": "Category A: Clear positive",
        "gold_label": "established/approved",
        "standard_gold": "SUPPORT",
        "epistemic_gold": "SUPPORT",
        "gold_source": "FDA Approved Drug Label (Norvasc)",
        "previously_evaluated": False,
        "previous_benchmark_source": "New",
        "special_stress_condition": "Calcium channel blocker positive control",
    },
    {
        "case_id": "TC-012",
        "drug": "Losartan",
        "disease": "Hypertension",
        "category": "Category A: Clear positive",
        "gold_label": "established/approved",
        "standard_gold": "SUPPORT",
        "epistemic_gold": "SUPPORT",
        "gold_source": "FDA Approved Drug Label (Cozaar)",
        "previously_evaluated": False,
        "previous_benchmark_source": "New",
        "special_stress_condition": "Angiotensin II receptor blocker positive control",
    },
    {
        "case_id": "TC-013",
        "drug": "Omeprazole",
        "disease": "GERD",
        "category": "Category A: Clear positive",
        "gold_label": "established/approved",
        "standard_gold": "SUPPORT",
        "epistemic_gold": "SUPPORT",
        "gold_source": "FDA Approved Drug Label (Prilosec)",
        "previously_evaluated": True,
        "previous_benchmark_source": "30-case holdout (H-002)",
        "special_stress_condition": "Proton pump inhibitor positive control",
    },
    {
        "case_id": "TC-014",
        "drug": "Sertraline",
        "disease": "Major depressive disorder",
        "category": "Category A: Clear positive",
        "gold_label": "established/approved",
        "standard_gold": "SUPPORT",
        "epistemic_gold": "SUPPORT",
        "gold_source": "FDA Approved Drug Label (Zoloft)",
        "previously_evaluated": True,
        "previous_benchmark_source": "30-case holdout (H-006)",
        "special_stress_condition": "SSRI antidepressant positive control",
    },
    {
        "case_id": "TC-015",
        "drug": "Albuterol",
        "disease": "Asthma",
        "category": "Category A: Clear positive",
        "gold_label": "established/approved",
        "standard_gold": "SUPPORT",
        "epistemic_gold": "SUPPORT",
        "gold_source": "FDA Approved Drug Label (Ventolin)",
        "previously_evaluated": False,
        "previous_benchmark_source": "New",
        "special_stress_condition": "Short-acting beta2-agonist bronchodilator",
    },
    {
        "case_id": "TC-016",
        "drug": "Warfarin",
        "disease": "Atrial fibrillation / stroke prevention",
        "category": "Category A: Clear positive",
        "gold_label": "established/approved",
        "standard_gold": "SUPPORT",
        "epistemic_gold": "SUPPORT",
        "gold_source": "FDA Approved Drug Label (Coumadin)",
        "previously_evaluated": False,
        "previous_benchmark_source": "New",
        "special_stress_condition": "Anticoagulant stroke prophylaxis in AFib",
    },
    {
        "case_id": "TC-017",
        "drug": "Methotrexate",
        "disease": "Rheumatoid arthritis",
        "category": "Category A: Clear positive",
        "gold_label": "established/approved",
        "standard_gold": "SUPPORT",
        "epistemic_gold": "SUPPORT",
        "gold_source": "FDA Approved Drug Label (Trexall)",
        "previously_evaluated": True,
        "previous_benchmark_source": "30-case holdout (H-007)",
        "special_stress_condition": "First-line DMARD positive control",
    },
    {
        "case_id": "TC-018",
        "drug": "Etanercept",
        "disease": "Rheumatoid arthritis",
        "category": "Category A: Clear positive",
        "gold_label": "established/approved",
        "standard_gold": "SUPPORT",
        "epistemic_gold": "SUPPORT",
        "gold_source": "FDA Approved Drug Label (Enbrel)",
        "previously_evaluated": True,
        "previous_benchmark_source": "25-case regression (CYN-036)",
        "special_stress_condition": "Biologic anti-TNF positive control; trial attribution test",
    },
    {
        "case_id": "TC-019",
        "drug": "Imatinib",
        "disease": "Chronic myeloid leukemia",
        "category": "Category A: Clear positive",
        "gold_label": "established/approved",
        "standard_gold": "SUPPORT",
        "epistemic_gold": "SUPPORT",
        "gold_source": "FDA Approved Drug Label (Gleevec)",
        "previously_evaluated": False,
        "previous_benchmark_source": "New (V1 benchmark positive)",
        "special_stress_condition": "Targeted BCR-ABL oncological positive control",
    },
    {
        "case_id": "TC-020",
        "drug": "Rituximab",
        "disease": "B-cell non-Hodgkin lymphoma",
        "category": "Category A: Clear positive",
        "gold_label": "established/approved",
        "standard_gold": "SUPPORT",
        "epistemic_gold": "SUPPORT",
        "gold_source": "FDA Approved Drug Label (Rituxan)",
        "previously_evaluated": True,
        "previous_benchmark_source": "30-case holdout (H-004)",
        "special_stress_condition": "Anti-CD20 targeted antibody in B-cell lymphoma",
    },

    # ── CATEGORY B: NEGATIVE / FAILED / HARD-NEGATIVE / UNCERTAIN (21-40) ──
    {
        "case_id": "TC-021",
        "drug": "Ivermectin",
        "disease": "COVID-19",
        "category": "Category B: Negative / failed / hard-negative",
        "gold_label": "negative/contradictory",
        "standard_gold": "OPPOSE",
        "epistemic_gold": "OPPOSE",
        "gold_source": "TOGETHER Trial (NEJM 2022); ACTIV-6 (JAMA 2022)",
        "previously_evaluated": True,
        "previous_benchmark_source": "30-case holdout (H-010)",
        "special_stress_condition": "Definitive clinical trial futility",
    },
    {
        "case_id": "TC-022",
        "drug": "Fluvoxamine",
        "disease": "COVID-19",
        "category": "Category B: Negative / failed / hard-negative",
        "gold_label": "negative/contradictory",
        "standard_gold": "OPPOSE",
        "epistemic_gold": "OPPOSE",
        "gold_source": "ACTIV-6 (JAMA 2023); COVID-OUT (NEJM 2022)",
        "previously_evaluated": True,
        "previous_benchmark_source": "25-case regression (CYN-109)",
        "special_stress_condition": "Conflicting/futility trial clinical evidence",
    },
    {
        "case_id": "TC-023",
        "drug": "Azithromycin",
        "disease": "COVID-19",
        "category": "Category B: Negative / failed / hard-negative",
        "gold_label": "negative/contradictory",
        "standard_gold": "OPPOSE",
        "epistemic_gold": "OPPOSE",
        "gold_source": "RECOVERY Trial (Lancet 2021); PRINCIPLE (Lancet 2021)",
        "previously_evaluated": True,
        "previous_benchmark_source": "25-case regression (CYN-103)",
        "special_stress_condition": "Definitive clinical failure in randomized trials",
    },
    {
        "case_id": "TC-024",
        "drug": "Hydroxychloroquine",
        "disease": "COVID-19",
        "category": "Category B: Negative / failed / hard-negative",
        "gold_label": "negative/contradictory",
        "standard_gold": "OPPOSE",
        "epistemic_gold": "OPPOSE",
        "gold_source": "RECOVERY Trial (NEJM 2020); WHO SOLIDARITY (NEJM 2021)",
        "previously_evaluated": True,
        "previous_benchmark_source": "30-case holdout (H-009)",
        "special_stress_condition": "High-profile trial futility & harm",
    },
    {
        "case_id": "TC-025",
        "drug": "Interferon beta-1a",
        "disease": "COVID-19",
        "category": "Category B: Negative / failed / hard-negative",
        "gold_label": "negative/contradictory",
        "standard_gold": "OPPOSE",
        "epistemic_gold": "OPPOSE",
        "gold_source": "WHO SOLIDARITY Trial (Lancet 2021)",
        "previously_evaluated": True,
        "previous_benchmark_source": "30-case holdout (H-015)",
        "special_stress_condition": "Multinational trial failure to improve mortality",
    },
    {
        "case_id": "TC-026",
        "drug": "Niacin",
        "disease": "Cardiovascular disease",
        "category": "Category B: Negative / failed / hard-negative",
        "gold_label": "negative/contradictory",
        "standard_gold": "OPPOSE",
        "epistemic_gold": "OPPOSE",
        "gold_source": "AIM-HIGH (NEJM 2011); HPS2-THRIVE (NEJM 2014)",
        "previously_evaluated": True,
        "previous_benchmark_source": "30-case holdout (H-013)",
        "special_stress_condition": "Definitive phase III trial futility on statin background",
    },
    {
        "case_id": "TC-027",
        "drug": "Doxorubicin",
        "disease": "Breast cancer",
        "category": "Category B: Negative / failed / hard-negative",
        "gold_label": "established/approved",
        "standard_gold": "SUPPORT",
        "epistemic_gold": "SUPPORT",
        "gold_source": "FDA Approved Indication (NDA 050464); NCCN Guidelines",
        "previously_evaluated": True,
        "previous_benchmark_source": "30-case holdout (H-008)",
        "special_stress_condition": "Stress control: Approved chemotherapeutic placed in negative group",
    },
    {
        "case_id": "TC-028",
        "drug": "Celecoxib",
        "disease": "Alzheimer's disease",
        "category": "Category B: Negative / failed / hard-negative",
        "gold_label": "negative/contradictory",
        "standard_gold": "OPPOSE",
        "epistemic_gold": "OPPOSE",
        "gold_source": "ADAPT Trial (Neurology 2008 / NEJM 2005)",
        "previously_evaluated": True,
        "previous_benchmark_source": "30-case holdout (H-011)",
        "special_stress_condition": "Trial termination for futility & cardiovascular safety",
    },
    {
        "case_id": "TC-029",
        "drug": "Simvastatin",
        "disease": "Sepsis",
        "category": "Category B: Negative / failed / hard-negative",
        "gold_label": "negative/contradictory",
        "standard_gold": "OPPOSE",
        "epistemic_gold": "OPPOSE",
        "gold_source": "ASEPSIS Trial; SAILS Trial (NEJM 2014)",
        "previously_evaluated": True,
        "previous_benchmark_source": "30-case holdout (H-012)",
        "special_stress_condition": "Failed randomized clinical trial in critical care",
    },
    {
        "case_id": "TC-030",
        "drug": "Dexamethasone",
        "disease": "Traumatic brain injury",
        "category": "Category B: Negative / failed / hard-negative",
        "gold_label": "negative/contradictory",
        "standard_gold": "OPPOSE",
        "epistemic_gold": "OPPOSE",
        "gold_source": "CRASH Trial (Lancet 2004, n=10,008: increased mortality)",
        "previously_evaluated": True,
        "previous_benchmark_source": "30-case holdout (H-014)",
        "special_stress_condition": "Direct therapeutic harm proven in landmark RCT",
    },
    {
        "case_id": "TC-031",
        "drug": "Furosemide",
        "disease": "Depression",
        "category": "Category B: Negative / failed / hard-negative",
        "gold_label": "unverified",
        "standard_gold": "OPPOSE",
        "epistemic_gold": "UNCERTAIN",
        "gold_source": "Absence of therapeutic mechanism / indication",
        "previously_evaluated": True,
        "previous_benchmark_source": "25-case regression (CYN-260)",
        "special_stress_condition": "Pure hard negative: UNKNOWN != NEGATIVE",
    },
    {
        "case_id": "TC-032",
        "drug": "Warfarin",
        "disease": "Leishmaniasis",
        "category": "Category B: Negative / failed / hard-negative",
        "gold_label": "unverified",
        "standard_gold": "OPPOSE",
        "epistemic_gold": "UNCERTAIN",
        "gold_source": "Absence of therapeutic mechanism / indication",
        "previously_evaluated": True,
        "previous_benchmark_source": "25-case regression (CYN-261)",
        "special_stress_condition": "Pure hard negative: UNKNOWN != NEGATIVE",
    },
    {
        "case_id": "TC-033",
        "drug": "Metformin",
        "disease": "Alzheimer's disease",
        "category": "Category B: Negative / failed / hard-negative",
        "gold_label": "insufficient/weak",
        "standard_gold": "UNCERTAIN",
        "epistemic_gold": "UNCERTAIN",
        "gold_source": "Mixed observational data / ongoing trials; no Phase 3 proof",
        "previously_evaluated": False,
        "previous_benchmark_source": "New",
        "special_stress_condition": "Hypothesis without verified Phase 3 clinical outcome",
    },
    {
        "case_id": "TC-034",
        "drug": "Aspirin",
        "disease": "Alzheimer's disease",
        "category": "Category B: Negative / failed / hard-negative",
        "gold_label": "negative/contradictory",
        "standard_gold": "OPPOSE",
        "epistemic_gold": "OPPOSE",
        "gold_source": "AD2000 Trial (Lancet 2008); ASPREE-NEURO (2020)",
        "previously_evaluated": False,
        "previous_benchmark_source": "New",
        "special_stress_condition": "Phase 3 clinical trial failure to prevent cognitive decline",
    },
    {
        "case_id": "TC-035",
        "drug": "Ivermectin",
        "disease": "Cancer",
        "category": "Category B: Negative / failed / hard-negative",
        "gold_label": "unverified",
        "standard_gold": "OPPOSE",
        "epistemic_gold": "UNCERTAIN",
        "gold_source": "In vitro artifacts only; no clinical oncology approval",
        "previously_evaluated": False,
        "previous_benchmark_source": "New",
        "special_stress_condition": "Preclinical in vitro trap / unverified hypothesis",
    },
    {
        "case_id": "TC-036",
        "drug": "Hydroxychloroquine",
        "disease": "Rheumatoid arthritis",
        "category": "Category B: Negative / failed / hard-negative",
        "gold_label": "established/approved",
        "standard_gold": "SUPPORT",
        "epistemic_gold": "SUPPORT",
        "gold_source": "FDA Approved Drug Label (Plaquenil)",
        "previously_evaluated": False,
        "previous_benchmark_source": "New (FDA approved positive control)",
        "special_stress_condition": "Stress control: Approved therapy placed in negative stress group",
    },
    {
        "case_id": "TC-037",
        "drug": "Azithromycin",
        "disease": "Asthma",
        "category": "Category B: Negative / failed / hard-negative",
        "gold_label": "insufficient/weak",
        "standard_gold": "UNCERTAIN",
        "epistemic_gold": "UNCERTAIN",
        "gold_source": "AMAZES Trial (Lancet 2017): phenotype specific add-on; not approved primary",
        "previously_evaluated": False,
        "previous_benchmark_source": "New",
        "special_stress_condition": "Contradictory / subtype-dependent non-approved add-on",
    },
    {
        "case_id": "TC-038",
        "drug": "Simvastatin",
        "disease": "Alzheimer's disease",
        "category": "Category B: Negative / failed / hard-negative",
        "gold_label": "negative/contradictory",
        "standard_gold": "OPPOSE",
        "epistemic_gold": "OPPOSE",
        "gold_source": "CLASP Trial (Neurology 2011, n=406: no cognitive benefit)",
        "previously_evaluated": False,
        "previous_benchmark_source": "New",
        "special_stress_condition": "Definitive clinical trial futility in dementia",
    },
    {
        "case_id": "TC-039",
        "drug": "Celecoxib",
        "disease": "Cancer",
        "category": "Category B: Negative / failed / hard-negative",
        "gold_label": "unverified",
        "standard_gold": "OPPOSE",
        "epistemic_gold": "UNCERTAIN",
        "gold_source": "Broad cancer claim unverified; FAP indication withdrawn",
        "previously_evaluated": False,
        "previous_benchmark_source": "New",
        "special_stress_condition": "General cancer broad claim without approved indication",
    },
    {
        "case_id": "TC-040",
        "drug": "Dexamethasone",
        "disease": "COVID-19",
        "category": "Category B: Negative / failed / hard-negative",
        "gold_label": "established/approved",
        "standard_gold": "SUPPORT",
        "epistemic_gold": "SUPPORT",
        "gold_source": "RECOVERY Trial (NEJM 2021); NIH/WHO Treatment Guidelines",
        "previously_evaluated": False,
        "previous_benchmark_source": "New (Standard of Care positive control)",
        "special_stress_condition": "Stress control: Proven life-saving SOC in negative stress group",
    },

    # ── CATEGORY C: CONTRADICTION / THERAPEUTIC DIRECTION / SAFETY (41-50) ──
    {
        "case_id": "TC-041",
        "drug": "Etanercept",
        "disease": "Sepsis",
        "category": "Category C: Contradiction / therapeutic direction / safety",
        "gold_label": "negative/contradictory",
        "standard_gold": "OPPOSE",
        "epistemic_gold": "OPPOSE",
        "gold_source": "Phase III Trial in Sepsis (NEJM 1997, increased mortality)",
        "previously_evaluated": False,
        "previous_benchmark_source": "New",
        "special_stress_condition": "Mechanistic anti-TNF rationale contradicted by clinical mortality",
    },
    {
        "case_id": "TC-042",
        "drug": "Infliximab",
        "disease": "Heart failure",
        "category": "Category C: Contradiction / therapeutic direction / safety",
        "gold_label": "negative/contradictory",
        "standard_gold": "OPPOSE",
        "epistemic_gold": "OPPOSE",
        "gold_source": "ATTACH Trial (Circulation 2003: worsened heart failure & death)",
        "previously_evaluated": False,
        "previous_benchmark_source": "New",
        "special_stress_condition": "Direct clinical contraindication / increased heart failure mortality",
    },
    {
        "case_id": "TC-043",
        "drug": "Rosiglitazone",
        "disease": "Type 2 diabetes",
        "category": "Category C: Contradiction / therapeutic direction / safety",
        "gold_label": "established/approved",
        "standard_gold": "SUPPORT",
        "epistemic_gold": "SUPPORT",
        "gold_source": "FDA Approved Drug Label (Avandia); RECORD Trial",
        "previously_evaluated": False,
        "previous_benchmark_source": "New",
        "special_stress_condition": "Efficacy approved with major cardiovascular safety black box",
    },
    {
        "case_id": "TC-044",
        "drug": "Rofecoxib",
        "disease": "Cardiovascular disease",
        "category": "Category C: Contradiction / therapeutic direction / safety",
        "gold_label": "negative/contradictory",
        "standard_gold": "OPPOSE",
        "epistemic_gold": "OPPOSE",
        "gold_source": "VIGOR Trial; APPROVe Trial (Withdrawn for CV thrombotic risk)",
        "previously_evaluated": False,
        "previous_benchmark_source": "New",
        "special_stress_condition": "Direct cardiovascular toxicity / black box withdrawal",
    },
    {
        "case_id": "TC-045",
        "drug": "Varenicline",
        "disease": "Smoking cessation",
        "category": "Category C: Contradiction / therapeutic direction / safety",
        "gold_label": "established/approved",
        "standard_gold": "SUPPORT",
        "epistemic_gold": "SUPPORT",
        "gold_source": "FDA Approved Drug Label (Chantix)",
        "previously_evaluated": False,
        "previous_benchmark_source": "New",
        "special_stress_condition": "Approved psychiatric/nicotinic agent with neuropsychiatric warnings",
    },
    {
        "case_id": "TC-046",
        "drug": "Propranolol",
        "disease": "Migraine",
        "category": "Category C: Contradiction / therapeutic direction / safety",
        "gold_label": "established/approved",
        "standard_gold": "SUPPORT",
        "epistemic_gold": "SUPPORT",
        "gold_source": "FDA Approved Drug Label (Inderal)",
        "previously_evaluated": False,
        "previous_benchmark_source": "New",
        "special_stress_condition": "Repurposed cardiovascular beta-blocker approved for migraine",
    },
    {
        "case_id": "TC-047",
        "drug": "Gabapentin",
        "disease": "Neuropathic pain",
        "category": "Category C: Contradiction / therapeutic direction / safety",
        "gold_label": "established/approved",
        "standard_gold": "SUPPORT",
        "epistemic_gold": "SUPPORT",
        "gold_source": "FDA Approved Drug Label (Neurontin)",
        "previously_evaluated": False,
        "previous_benchmark_source": "New",
        "special_stress_condition": "Approved anticonvulsant repurposed for neuropathic pain",
    },
    {
        "case_id": "TC-048",
        "drug": "Pregabalin",
        "disease": "Fibromyalgia",
        "category": "Category C: Contradiction / therapeutic direction / safety",
        "gold_label": "established/approved",
        "standard_gold": "SUPPORT",
        "epistemic_gold": "SUPPORT",
        "gold_source": "FDA Approved Drug Label (Lyrica)",
        "previously_evaluated": False,
        "previous_benchmark_source": "New",
        "special_stress_condition": "Approved voltage-gated calcium channel modulator",
    },
    {
        "case_id": "TC-049",
        "drug": "Colchicine",
        "disease": "Gout",
        "category": "Category C: Contradiction / therapeutic direction / safety",
        "gold_label": "established/approved",
        "standard_gold": "SUPPORT",
        "epistemic_gold": "SUPPORT",
        "gold_source": "FDA Approved Drug Label (Colcrys)",
        "previously_evaluated": False,
        "previous_benchmark_source": "New",
        "special_stress_condition": "Anti-tubulin anti-inflammatory approved for acute gout",
    },
    {
        "case_id": "TC-050",
        "drug": "Allopurinol",
        "disease": "Gout",
        "category": "Category C: Contradiction / therapeutic direction / safety",
        "gold_label": "established/approved",
        "standard_gold": "SUPPORT",
        "epistemic_gold": "SUPPORT",
        "gold_source": "FDA Approved Drug Label (Zyloprim)",
        "previously_evaluated": False,
        "previous_benchmark_source": "New",
        "special_stress_condition": "Xanthine oxidase inhibitor approved for chronic gout",
    },

    # ── CATEGORY D: CANCER / SUBTYPE / BIOMARKER / CLINICAL EVIDENCE (51-60) ──
    {
        "case_id": "TC-051",
        "drug": "Valproic acid",
        "disease": "Glioblastoma",
        "category": "Category D: Cancer / subtype / biomarker / clinical evidence",
        "gold_label": "insufficient/weak",
        "standard_gold": "UNCERTAIN",
        "epistemic_gold": "UNCERTAIN",
        "gold_source": "Preclinical HDAC inhibition; no Phase 3 RCT survival benefit",
        "previously_evaluated": True,
        "previous_benchmark_source": "30-case holdout (H-026)",
        "special_stress_condition": "Weak indirect evidence / unproven repurposing candidate",
    },
    {
        "case_id": "TC-052",
        "drug": "Nivolumab",
        "disease": "Glioblastoma",
        "category": "Category D: Cancer / subtype / biomarker / clinical evidence",
        "gold_label": "negative/contradictory",
        "standard_gold": "OPPOSE",
        "epistemic_gold": "OPPOSE",
        "gold_source": "CheckMate 143 Phase 3 RCT (Lancet Oncol 2020: no OS benefit)",
        "previously_evaluated": False,
        "previous_benchmark_source": "New",
        "special_stress_condition": "Definitive phase 3 checkpoint inhibitor clinical trial failure",
    },
    {
        "case_id": "TC-053",
        "drug": "Pembrolizumab",
        "disease": "Glioblastoma",
        "category": "Category D: Cancer / subtype / biomarker / clinical evidence",
        "gold_label": "negative/contradictory",
        "standard_gold": "OPPOSE",
        "epistemic_gold": "OPPOSE",
        "gold_source": "Phase 2/3 trials (e.g. Cloughesy et al. 2019 / Keynote): no survival benefit",
        "previously_evaluated": False,
        "previous_benchmark_source": "New",
        "special_stress_condition": "Clinical failure of PD-1 blockade in unselected glioblastoma",
    },
    {
        "case_id": "TC-054",
        "drug": "Bevacizumab",
        "disease": "Glioblastoma",
        "category": "Category D: Cancer / subtype / biomarker / clinical evidence",
        "gold_label": "established/approved",
        "standard_gold": "SUPPORT",
        "epistemic_gold": "SUPPORT",
        "gold_source": "FDA Accelerated Approval (Avastin for recurrent glioblastoma)",
        "previously_evaluated": False,
        "previous_benchmark_source": "New",
        "special_stress_condition": "Approved anti-VEGF for recurrent glioblastoma with PFS benefit",
    },
    {
        "case_id": "TC-055",
        "drug": "Erlotinib",
        "disease": "Non-small-cell lung cancer",
        "category": "Category D: Cancer / subtype / biomarker / clinical evidence",
        "gold_label": "established/approved",
        "standard_gold": "SUPPORT",
        "epistemic_gold": "SUPPORT",
        "gold_source": "FDA Approved Drug Label (Tarceva)",
        "previously_evaluated": False,
        "previous_benchmark_source": "New",
        "special_stress_condition": "First-generation EGFR TKI in NSCLC",
    },
    {
        "case_id": "TC-056",
        "drug": "Gefitinib",
        "disease": "EGFR-positive lung cancer",
        "category": "Category D: Cancer / subtype / biomarker / clinical evidence",
        "gold_label": "established/approved",
        "standard_gold": "SUPPORT",
        "epistemic_gold": "SUPPORT",
        "gold_source": "FDA Approved Drug Label (Iressa)",
        "previously_evaluated": False,
        "previous_benchmark_source": "New",
        "special_stress_condition": "Biomarker-specific EGFR exon 19/21 lung cancer therapy",
    },
    {
        "case_id": "TC-057",
        "drug": "Osimertinib",
        "disease": "EGFR-mutant lung cancer",
        "category": "Category D: Cancer / subtype / biomarker / clinical evidence",
        "gold_label": "established/approved",
        "standard_gold": "SUPPORT",
        "epistemic_gold": "SUPPORT",
        "gold_source": "FDA Approved Drug Label (Tagrisso); FLAURA Trial",
        "previously_evaluated": False,
        "previous_benchmark_source": "New",
        "special_stress_condition": "Third-generation mutant-selective EGFR inhibitor",
    },
    {
        "case_id": "TC-058",
        "drug": "Crizotinib",
        "disease": "ALK-positive lung cancer",
        "category": "Category D: Cancer / subtype / biomarker / clinical evidence",
        "gold_label": "established/approved",
        "standard_gold": "SUPPORT",
        "epistemic_gold": "SUPPORT",
        "gold_source": "FDA Approved Drug Label (Xalkori)",
        "previously_evaluated": False,
        "previous_benchmark_source": "New",
        "special_stress_condition": "Biomarker-defined ALK/ROS1 targeted lung cancer therapy",
    },
    {
        "case_id": "TC-059",
        "drug": "Bortezomib",
        "disease": "Multiple myeloma",
        "category": "Category D: Cancer / subtype / biomarker / clinical evidence",
        "gold_label": "established/approved",
        "standard_gold": "SUPPORT",
        "epistemic_gold": "SUPPORT",
        "gold_source": "FDA Approved Drug Label (Velcade)",
        "previously_evaluated": False,
        "previous_benchmark_source": "New",
        "special_stress_condition": "Proteasome inhibitor oncology standard of care",
    },
    {
        "case_id": "TC-060",
        "drug": "Lenalidomide",
        "disease": "Multiple myeloma",
        "category": "Category D: Cancer / subtype / biomarker / clinical evidence",
        "gold_label": "established/approved",
        "standard_gold": "SUPPORT",
        "epistemic_gold": "SUPPORT",
        "gold_source": "FDA Approved Drug Label (Revlimid)",
        "previously_evaluated": False,
        "previous_benchmark_source": "New",
        "special_stress_condition": "Immunomodulatory cereblon ligand in hematologic malignancy",
    },

    # ── CATEGORY E: MECHANISTIC / OFF-LABEL / MULTI-TARGET (61-70) ──
    {
        "case_id": "TC-061",
        "drug": "Bevacizumab",
        "disease": "Age-related macular degeneration",
        "category": "Category E: Mechanistic / off-label / multi-target",
        "gold_label": "established/approved",
        "standard_gold": "SUPPORT",
        "epistemic_gold": "SUPPORT",
        "gold_source": "CATT Landmark Trial (NEJM 2011); Standard of Care Off-Label",
        "previously_evaluated": False,
        "previous_benchmark_source": "New",
        "special_stress_condition": "Landmark off-label standard of care anti-VEGF",
    },
    {
        "case_id": "TC-062",
        "drug": "Ranibizumab",
        "disease": "Age-related macular degeneration",
        "category": "Category E: Mechanistic / off-label / multi-target",
        "gold_label": "established/approved",
        "standard_gold": "SUPPORT",
        "epistemic_gold": "SUPPORT",
        "gold_source": "FDA Approved Drug Label (Lucentis)",
        "previously_evaluated": False,
        "previous_benchmark_source": "New",
        "special_stress_condition": "FDA approved anti-VEGF Fab fragment for wet AMD",
    },
    {
        "case_id": "TC-063",
        "drug": "Latanoprost",
        "disease": "Glaucoma",
        "category": "Category E: Mechanistic / off-label / multi-target",
        "gold_label": "established/approved",
        "standard_gold": "SUPPORT",
        "epistemic_gold": "SUPPORT",
        "gold_source": "FDA Approved Drug Label (Xalatan)",
        "previously_evaluated": False,
        "previous_benchmark_source": "New",
        "special_stress_condition": "Prostaglandin analogue reducing intraocular pressure",
    },
    {
        "case_id": "TC-064",
        "drug": "Timolol",
        "disease": "Glaucoma",
        "category": "Category E: Mechanistic / off-label / multi-target",
        "gold_label": "established/approved",
        "standard_gold": "SUPPORT",
        "epistemic_gold": "SUPPORT",
        "gold_source": "FDA Approved Drug Label (Timoptic)",
        "previously_evaluated": False,
        "previous_benchmark_source": "New",
        "special_stress_condition": "Beta-blocker reducing aqueous humor production",
    },
    {
        "case_id": "TC-065",
        "drug": "Sildenafil",
        "disease": "Pulmonary arterial hypertension",
        "category": "Category E: Mechanistic / off-label / multi-target",
        "gold_label": "established/approved",
        "standard_gold": "SUPPORT",
        "epistemic_gold": "SUPPORT",
        "gold_source": "FDA Approved Drug Label (Revatio)",
        "previously_evaluated": False,
        "previous_benchmark_source": "New",
        "special_stress_condition": "Landmark cardiovascular repurposing of PDE5 inhibitor",
    },
    {
        "case_id": "TC-066",
        "drug": "Sildenafil",
        "disease": "Alzheimer's disease",
        "category": "Category E: Mechanistic / off-label / multi-target",
        "gold_label": "unverified",
        "standard_gold": "OPPOSE",
        "epistemic_gold": "UNCERTAIN",
        "gold_source": "Preclinical/computational claims; unverified in randomized clinical trials",
        "previously_evaluated": False,
        "previous_benchmark_source": "New",
        "special_stress_condition": "Mechanistic computational hypothesis without clinical validation",
    },
    {
        "case_id": "TC-067",
        "drug": "Sildenafil",
        "disease": "Heart failure",
        "category": "Category E: Mechanistic / off-label / multi-target",
        "gold_label": "negative/contradictory",
        "standard_gold": "OPPOSE",
        "epistemic_gold": "OPPOSE",
        "gold_source": "RELAX Trial (JAMA 2013: no benefit in HFpEF)",
        "previously_evaluated": False,
        "previous_benchmark_source": "New",
        "special_stress_condition": "Clinical trial futility in heart failure with preserved ejection fraction",
    },
    {
        "case_id": "TC-068",
        "drug": "Spironolactone",
        "disease": "Heart failure",
        "category": "Category E: Mechanistic / off-label / multi-target",
        "gold_label": "established/approved",
        "standard_gold": "SUPPORT",
        "epistemic_gold": "SUPPORT",
        "gold_source": "RALES Landmark Trial (NEJM 1999); FDA Approved Label",
        "previously_evaluated": False,
        "previous_benchmark_source": "New",
        "special_stress_condition": "Mineralocorticoid receptor antagonist mortality benefit",
    },
    {
        "case_id": "TC-069",
        "drug": "Digoxin",
        "disease": "Heart failure",
        "category": "Category E: Mechanistic / off-label / multi-target",
        "gold_label": "established/approved",
        "standard_gold": "SUPPORT",
        "epistemic_gold": "SUPPORT",
        "gold_source": "DIG Trial (NEJM 1997); FDA Approved Label (Lanoxin)",
        "previously_evaluated": False,
        "previous_benchmark_source": "New",
        "special_stress_condition": "Cardiac glycoside approved for symptom control/hospitalization reduction",
    },
    {
        "case_id": "TC-070",
        "drug": "Verapamil",
        "disease": "Migraine",
        "category": "Category E: Mechanistic / off-label / multi-target",
        "gold_label": "insufficient/weak",
        "standard_gold": "UNCERTAIN",
        "epistemic_gold": "UNCERTAIN",
        "gold_source": "Off-label guideline prophylaxis; inconclusive Phase 3 evidence",
        "previously_evaluated": False,
        "previous_benchmark_source": "New",
        "special_stress_condition": "Off-label prophylactic calcium blocker without conclusive trial proof",
    },

    # ── CATEGORY F: MULTI-TARGET / METABOLIC / CARDIOVASCULAR (71-80) ──
    {
        "case_id": "TC-071",
        "drug": "Dapagliflozin",
        "disease": "Heart failure",
        "category": "Category F: Multi-target / metabolic / cardiovascular",
        "gold_label": "established/approved",
        "standard_gold": "SUPPORT",
        "epistemic_gold": "SUPPORT",
        "gold_source": "DAPA-HF Trial (NEJM 2019); FDA Approved Indication (Farxiga)",
        "previously_evaluated": False,
        "previous_benchmark_source": "New (V1 benchmark positive)",
        "special_stress_condition": "SGLT2 inhibitor metabolic to cardiovascular repurposing",
    },
    {
        "case_id": "TC-072",
        "drug": "Empagliflozin",
        "disease": "Heart failure",
        "category": "Category F: Multi-target / metabolic / cardiovascular",
        "gold_label": "established/approved",
        "standard_gold": "SUPPORT",
        "epistemic_gold": "SUPPORT",
        "gold_source": "EMPEROR-Reduced / EMPEROR-Preserved (NEJM 2020/2021); FDA Approved",
        "previously_evaluated": False,
        "previous_benchmark_source": "New",
        "special_stress_condition": "SGLT2 inhibitor approved for heart failure across ejection fractions",
    },
    {
        "case_id": "TC-073",
        "drug": "Semaglutide",
        "disease": "Type 2 diabetes",
        "category": "Category F: Multi-target / metabolic / cardiovascular",
        "gold_label": "established/approved",
        "standard_gold": "SUPPORT",
        "epistemic_gold": "SUPPORT",
        "gold_source": "FDA Approved Drug Label (Ozempic/Rybelsus)",
        "previously_evaluated": False,
        "previous_benchmark_source": "New",
        "special_stress_condition": "GLP-1 receptor agonist metabolic positive control",
    },
    {
        "case_id": "TC-074",
        "drug": "Semaglutide",
        "disease": "Alzheimer's disease",
        "category": "Category F: Multi-target / metabolic / cardiovascular",
        "gold_label": "unverified",
        "standard_gold": "OPPOSE",
        "epistemic_gold": "UNCERTAIN",
        "gold_source": "Investigational Phase 3 underway (EVOKE); not established or approved",
        "previously_evaluated": False,
        "previous_benchmark_source": "New",
        "special_stress_condition": "Investigational hypothesis without completed outcome data",
    },
    {
        "case_id": "TC-075",
        "drug": "Pioglitazone",
        "disease": "Alzheimer's disease",
        "category": "Category F: Multi-target / metabolic / cardiovascular",
        "gold_label": "negative/contradictory",
        "standard_gold": "OPPOSE",
        "epistemic_gold": "OPPOSE",
        "gold_source": "TOMMORROW Phase 3 Trial (Alzheimers Dement 2021: futility/stopped)",
        "previously_evaluated": False,
        "previous_benchmark_source": "New",
        "special_stress_condition": "Failed Phase 3 randomized trial in dementia prevention",
    },
    {
        "case_id": "TC-076",
        "drug": "Statin",
        "disease": "Sepsis",
        "category": "Category F: Multi-target / metabolic / cardiovascular",
        "gold_label": "negative/contradictory",
        "standard_gold": "OPPOSE",
        "epistemic_gold": "OPPOSE",
        "gold_source": "SAILS / ASEPSIS meta-analyses: no mortality benefit",
        "previously_evaluated": False,
        "previous_benchmark_source": "New",
        "special_stress_condition": "Class-level negative clinical trial outcome",
    },
    {
        "case_id": "TC-077",
        "drug": "Atorvastatin",
        "disease": "Cardiovascular disease",
        "category": "Category F: Multi-target / metabolic / cardiovascular",
        "gold_label": "established/approved",
        "standard_gold": "SUPPORT",
        "epistemic_gold": "SUPPORT",
        "gold_source": "FDA Approved Drug Label (Lipitor); ASCOT-LLA Trial",
        "previously_evaluated": False,
        "previous_benchmark_source": "New",
        "special_stress_condition": "Landmark lipid-lowering cardiovascular risk reduction",
    },
    {
        "case_id": "TC-078",
        "drug": "Simvastatin",
        "disease": "Cardiovascular disease",
        "category": "Category F: Multi-target / metabolic / cardiovascular",
        "gold_label": "established/approved",
        "standard_gold": "SUPPORT",
        "epistemic_gold": "SUPPORT",
        "gold_source": "4S Landmark Trial (Lancet 1994); FDA Approved Drug Label",
        "previously_evaluated": False,
        "previous_benchmark_source": "New",
        "special_stress_condition": "Landmark survival trial in coronary heart disease",
    },
    {
        "case_id": "TC-079",
        "drug": "Fenofibrate",
        "disease": "Cardiovascular disease",
        "category": "Category F: Multi-target / metabolic / cardiovascular",
        "gold_label": "negative/contradictory",
        "standard_gold": "OPPOSE",
        "epistemic_gold": "OPPOSE",
        "gold_source": "FIELD Trial (Lancet 2005); ACCORD-Lipid (NEJM 2010): no primary CVD reduction",
        "previously_evaluated": False,
        "previous_benchmark_source": "New",
        "special_stress_condition": "Phase 3 clinical trial failure on primary cardiovascular endpoints",
    },
    {
        "case_id": "TC-080",
        "drug": "Ezetimibe",
        "disease": "Cardiovascular disease",
        "category": "Category F: Multi-target / metabolic / cardiovascular",
        "gold_label": "established/approved",
        "standard_gold": "SUPPORT",
        "epistemic_gold": "SUPPORT",
        "gold_source": "IMPROVE-IT Landmark Trial (NEJM 2015); FDA Approved Label (Zetia)",
        "previously_evaluated": False,
        "previous_benchmark_source": "New",
        "special_stress_condition": "NPC1L1 cholesterol absorption inhibitor with proven CVD reduction",
    },

    # ── CATEGORY G: SAFETY / VETO / CONTRADICTION (81-90) ──
    {
        "case_id": "TC-081",
        "drug": "Warfarin",
        "disease": "Bleeding disorder",
        "category": "Category G: Safety / veto / contradiction",
        "gold_label": "negative/contradictory",
        "standard_gold": "OPPOSE",
        "epistemic_gold": "OPPOSE",
        "gold_source": "Absolute Contraindication / FDA Black Box (Exacerbates hemorrhage)",
        "previously_evaluated": False,
        "previous_benchmark_source": "New",
        "special_stress_condition": "Absolute pharmacological contraindication / safety veto",
    },
    {
        "case_id": "TC-082",
        "drug": "Aspirin",
        "disease": "Hemorrhagic stroke",
        "category": "Category G: Safety / veto / contradiction",
        "gold_label": "negative/contradictory",
        "standard_gold": "OPPOSE",
        "epistemic_gold": "OPPOSE",
        "gold_source": "Absolute Contraindication (Antiplatelet worsens intracranial bleeding)",
        "previously_evaluated": False,
        "previous_benchmark_source": "New",
        "special_stress_condition": "Absolute safety contraindication / lethal exacerbation",
    },
    {
        "case_id": "TC-083",
        "drug": "NSAIDs",
        "disease": "Peptic ulcer disease",
        "category": "Category G: Safety / veto / contradiction",
        "gold_label": "negative/contradictory",
        "standard_gold": "OPPOSE",
        "epistemic_gold": "OPPOSE",
        "gold_source": "Class Black Box Warning / Causative etiology for gastric mucosal ulceration",
        "previously_evaluated": False,
        "previous_benchmark_source": "New",
        "special_stress_condition": "Etiological cause of disease rather than treatment",
    },
    {
        "case_id": "TC-084",
        "drug": "Methotrexate",
        "disease": "Pregnancy-related condition",
        "category": "Category G: Safety / veto / contradiction",
        "gold_label": "negative/contradictory",
        "standard_gold": "OPPOSE",
        "epistemic_gold": "OPPOSE",
        "gold_source": "FDA Boxed Warning (Category X: Teratogenic and embryotoxic)",
        "previously_evaluated": False,
        "previous_benchmark_source": "New",
        "special_stress_condition": "Teratogenic safety veto / absolute contraindication",
    },
    {
        "case_id": "TC-085",
        "drug": "Isotretinoin",
        "disease": "Pregnancy",
        "category": "Category G: Safety / veto / contradiction",
        "gold_label": "negative/contradictory",
        "standard_gold": "OPPOSE",
        "epistemic_gold": "OPPOSE",
        "gold_source": "FDA Boxed Warning / iPLEDGE (Severe birth defects / teratogen)",
        "previously_evaluated": False,
        "previous_benchmark_source": "New",
        "special_stress_condition": "Severe teratogen / absolute contraindication in pregnancy",
    },
    {
        "case_id": "TC-086",
        "drug": "Clozapine",
        "disease": "Schizophrenia",
        "category": "Category G: Safety / veto / contradiction",
        "gold_label": "established/approved",
        "standard_gold": "SUPPORT",
        "epistemic_gold": "SUPPORT",
        "gold_source": "FDA Approved Drug Label (Clozaril, with REMS for agranulocytosis)",
        "previously_evaluated": False,
        "previous_benchmark_source": "New",
        "special_stress_condition": "Approved gold-standard atypical antipsychotic with severe safety warnings",
    },
    {
        "case_id": "TC-087",
        "drug": "Thalidomide",
        "disease": "Multiple myeloma",
        "category": "Category G: Safety / veto / contradiction",
        "gold_label": "established/approved",
        "standard_gold": "SUPPORT",
        "epistemic_gold": "SUPPORT",
        "gold_source": "FDA Approved Drug Label (Thalomid, with REMS for teratogenicity)",
        "previously_evaluated": False,
        "previous_benchmark_source": "New",
        "special_stress_condition": "Repurposed teratogen approved for hematological cancer",
    },
    {
        "case_id": "TC-088",
        "drug": "Doxorubicin",
        "disease": "Cardiomyopathy",
        "category": "Category G: Safety / veto / contradiction",
        "gold_label": "negative/contradictory",
        "standard_gold": "OPPOSE",
        "epistemic_gold": "OPPOSE",
        "gold_source": "FDA Boxed Warning (Dose-dependent cardiotoxicity causes cardiomyopathy)",
        "previously_evaluated": False,
        "previous_benchmark_source": "New",
        "special_stress_condition": "Direct causative toxic etiology / contraindication",
    },
    {
        "case_id": "TC-089",
        "drug": "Digoxin",
        "disease": "Atrial fibrillation",
        "category": "Category G: Safety / veto / contradiction",
        "gold_label": "established/approved",
        "standard_gold": "SUPPORT",
        "epistemic_gold": "SUPPORT",
        "gold_source": "FDA Approved Drug Label (Lanoxin for ventricular rate control)",
        "previously_evaluated": False,
        "previous_benchmark_source": "New",
        "special_stress_condition": "Approved rate-control agent with narrow therapeutic window",
    },
    {
        "case_id": "TC-090",
        "drug": "Amiodarone",
        "disease": "Atrial fibrillation",
        "category": "Category G: Safety / veto / contradiction",
        "gold_label": "established/approved",
        "standard_gold": "SUPPORT",
        "epistemic_gold": "SUPPORT",
        "gold_source": "FDA Approved / ACC/AHA Guidelines Class III Antiarrhythmic",
        "previously_evaluated": False,
        "previous_benchmark_source": "New",
        "special_stress_condition": "Approved antiarrhythmic with multiorgan pulmonary/thyroid toxicity",
    },

    # ── CATEGORY H: CLINICAL TRIAL ATTRIBUTION / COMBINATION / REGISTRY (91-100) ──
    {
        "case_id": "TC-091",
        "drug": "Budesonide/Formoterol",
        "disease": "Asthma",
        "category": "Category H: Clinical trial attribution / combination / registry",
        "gold_label": "established/approved",
        "standard_gold": "SUPPORT",
        "epistemic_gold": "SUPPORT",
        "gold_source": "FDA Approved Drug Label (Symbicort)",
        "previously_evaluated": False,
        "previous_benchmark_source": "New",
        "special_stress_condition": "Fixed-dose combination therapy attribution test",
    },
    {
        "case_id": "TC-092",
        "drug": "Budesonide",
        "disease": "COPD",
        "category": "Category H: Clinical trial attribution / combination / registry",
        "gold_label": "established/approved",
        "standard_gold": "SUPPORT",
        "epistemic_gold": "SUPPORT",
        "gold_source": "FDA Approved Drug Label / GOLD Guidelines",
        "previously_evaluated": False,
        "previous_benchmark_source": "New",
        "special_stress_condition": "Inhaled steroid trial attribution in COPD",
    },
    {
        "case_id": "TC-093",
        "drug": "Metformin",
        "disease": "Type 2 diabetes",
        "category": "Category H: Clinical trial attribution / combination / registry",
        "gold_label": "established/approved",
        "standard_gold": "SUPPORT",
        "epistemic_gold": "SUPPORT",
        "gold_source": "FDA Approved Drug Label (Glucophage)",
        "previously_evaluated": True,
        "previous_benchmark_source": "Repeated test (Attribution & background therapy)",
        "special_stress_condition": "Background therapy attribution stress test (Rule -1)",
    },
    {
        "case_id": "TC-094",
        "drug": "Warfarin",
        "disease": "Thrombosis",
        "category": "Category H: Clinical trial attribution / combination / registry",
        "gold_label": "established/approved",
        "standard_gold": "SUPPORT",
        "epistemic_gold": "SUPPORT",
        "gold_source": "FDA Approved Drug Label (Coumadin)",
        "previously_evaluated": False,
        "previous_benchmark_source": "New",
        "special_stress_condition": "Anticoagulant trial outcome attribution in thrombosis",
    },
    {
        "case_id": "TC-095",
        "drug": "Heparin",
        "disease": "Thrombosis",
        "category": "Category H: Clinical trial attribution / combination / registry",
        "gold_label": "established/approved",
        "standard_gold": "SUPPORT",
        "epistemic_gold": "SUPPORT",
        "gold_source": "FDA Approved Drug Label",
        "previously_evaluated": False,
        "previous_benchmark_source": "New",
        "special_stress_condition": "Standard acute anticoagulant clinical trial attribution",
    },
    {
        "case_id": "TC-096",
        "drug": "Placebo",
        "disease": "Disease treatment",
        "category": "Category H: Clinical trial attribution / combination / registry",
        "gold_label": "unverified",
        "standard_gold": "OPPOSE",
        "epistemic_gold": "OPPOSE",
        "gold_source": "Pharmacological control entity (inactive comparator)",
        "previously_evaluated": False,
        "previous_benchmark_source": "New",
        "special_stress_condition": "Negative control entity / comparator role stress test",
    },
    {
        "case_id": "TC-097",
        "drug": "Etanercept",
        "disease": "Rheumatoid arthritis",
        "category": "Category H: Clinical trial attribution / combination / registry",
        "gold_label": "established/approved",
        "standard_gold": "SUPPORT",
        "epistemic_gold": "SUPPORT",
        "gold_source": "FDA Approved Drug Label (Enbrel)",
        "previously_evaluated": True,
        "previous_benchmark_source": "Repeated test (Autoinjector attribution)",
        "special_stress_condition": "Device / autoinjector trial attribution isolation (NCT01875991)",
    },
    {
        "case_id": "TC-098",
        "drug": "Fluticasone",
        "disease": "Allergic rhinitis",
        "category": "Category H: Clinical trial attribution / combination / registry",
        "gold_label": "established/approved",
        "standard_gold": "SUPPORT",
        "epistemic_gold": "SUPPORT",
        "gold_source": "FDA Approved Drug Label (Flonase)",
        "previously_evaluated": True,
        "previous_benchmark_source": "Repeated test (Registry only vs active trial)",
        "special_stress_condition": "Registry trial outcome separation stress test",
    },
    {
        "case_id": "TC-099",
        "drug": "Tamoxifen",
        "disease": "Breast cancer",
        "category": "Category H: Clinical trial attribution / combination / registry",
        "gold_label": "established/approved",
        "standard_gold": "SUPPORT",
        "epistemic_gold": "SUPPORT",
        "gold_source": "FDA Approved Drug Label (Nolvadex)",
        "previously_evaluated": False,
        "previous_benchmark_source": "New",
        "special_stress_condition": "Broad disease term matching subtype approval",
    },
    {
        "case_id": "TC-100",
        "drug": "Trastuzumab",
        "disease": "HER2-positive breast cancer",
        "category": "Category H: Clinical trial attribution / combination / registry",
        "gold_label": "established/approved",
        "standard_gold": "SUPPORT",
        "epistemic_gold": "SUPPORT",
        "gold_source": "FDA Approved Drug Label (Herceptin)",
        "previously_evaluated": True,
        "previous_benchmark_source": "Repeated test (Subtype indication matching)",
        "special_stress_condition": "Combination trial attribution & subtype matching",
    },
]

print(f"Manifest created with {len(MANIFEST)} cases.")
with open("scratch/manifest_100_cases.json", "w") as f:
    json.dump(MANIFEST, f, indent=2)

# Print Summary
prev_count = sum(1 for c in MANIFEST if c["previously_evaluated"])
new_count = sum(1 for c in MANIFEST if not c["previously_evaluated"])
print(f"TOTAL_CASES = {len(MANIFEST)}")
print(f"PREVIOUSLY_SEEN_CASES = {prev_count}")
print(f"NEW_CASES = {new_count}")
print(f"SUBSTITUTIONS = 0")
print(f"UNAVAILABLE = 0")
