import json
import re
import sys
from pathlib import Path

sys.path.insert(0, ".")

from backend.core.domain.drug import Drug
from backend.core.domain.disease import Disease
from backend.core.enums.recommendation import RecommendationStatus
from backend.evaluation.benchmark_models import BenchmarkClass, map_recommendation_to_class
from backend.engineering.orchestrator.master_orchestrator import MasterOrchestrator
from backend.engineering.retrieval.disease_relation import matches_for_approval_anchor
from backend.reasoning.opposition.therapeutic_opposition_assessor import (
    TherapeuticOppositionAssessor,
    trial_to_negative_claim,
)
from backend.engineering.retrieval.pipeline import RetrievalPipeline
from backend.reasoning.orchestrator.decision_rules import apply_decision_rules
from backend.evaluation.run_50_case_post_clinicaltrials_fast import apply_decision_rules as fast_apply_rules

def run_tc062_through_all_evaluation_paths():
    drug = "Ranibizumab"
    disease = "Age-related macular degeneration"
    cid = "TC-062"

    results = []

    # 1. Canonical Production Record (from results.jsonl regenerated by MasterOrchestrator)
    prod_rec = None
    with open("evaluation_outputs/100_case_final/results.jsonl", "r", encoding="utf-8") as f:
        for line in f:
            d = json.loads(line)
            if d.get("case_id") == cid:
                prod_rec = d
                break
    assert prod_rec is not None, "TC-062 not found in results.jsonl"

    m_term_prod = re.search(r"Matched ChEMBL term: '([^']+)'", str(prod_rec.get("decision_rule", "")))
    matched_term_prod = m_term_prod.group(1) if m_term_prod else prod_rec.get("matched_indication_term")
    prod_is_anchor = matches_for_approval_anchor(disease, matched_term_prod) if matched_term_prod else False

    # Extract authoritative deciding rule from recommendation_reasons (matching DecisionResult.deciding_rule)
    dec_rule_prod = None
    for r in reversed(prod_rec.get("recommendation_reasons", [])):
        if r.startswith("Rule ") and not r.startswith("Rule -1 (APPROVED INDICATION ANCHOR)"):
            dec_rule_prod = r.split(":")[0].strip()
            break
    if not dec_rule_prod:
        dec_rule_prod = prod_rec["decision_rule"].split(":")[0].strip()

    results.append({
        "path": "Production (Canonical MasterOrchestrator)",
        "prediction": prod_rec["prediction"],
        "recommendation_status": prod_rec["recommendation"],
        "opposition_score": prod_rec["opposition_score"],
        "approved_indication_detected": prod_is_anchor,
        "decision_rule": dec_rule_prod,
        "matched_term": matched_term_prod,
    })

    # 2. Fast Evaluator Path
    # Uses cached trials + canonical record from results.jsonl
    cache_path = Path(f"data/ct_raw_cache/{drug}_{disease.replace(' ', '_').replace('-', '_')}.json")
    if not cache_path.exists():
        cache_path = Path("data/ct_raw_cache/Ranibizumab_Age_related_macular_degeneration.json")
    raw_ct = json.loads(cache_path.read_text(encoding="utf-8"))
    pipe = RetrievalPipeline()
    parsed_trials = pipe._parse_trials_data(
        raw_ct,
        Drug(name=drug, identifiers={"chembl": "CHEMBL1201825"}),
        Disease(name=disease, identifiers={"mesh": "D008268"}),
    )
    claims = [trial_to_negative_claim(t, drug, disease) for t in parsed_trials]
    claims = [c for c in claims if c]
    opp_assessor = TherapeuticOppositionAssessor()
    opp_assess = opp_assessor.assess(claims, drug, disease)

    baseline_rule = str(prod_rec.get("decision_rule", ""))
    m_term_fast = re.search(r"Matched ChEMBL term: '([^']+)'", baseline_rule)
    matched_term_fast = m_term_fast.group(1) if m_term_fast else (prod_rec.get("matched_indication_term") or None)
    fast_is_anchor = matches_for_approval_anchor(disease, matched_term_fast) if matched_term_fast else False

    fast_dec = fast_apply_rules(
        is_approved=fast_is_anchor,
        matched_chembl_term=matched_term_fast,
        support_score=float(prod_rec.get("support_score", 0.0)),
        mechanistic_score=float(prod_rec.get("mechanistic_score", 0.0)),
        risk_score=float(prod_rec.get("risk_score", 0.0)),
        opp_assessment=opp_assess,
    )
    fast_pred = "SUPPORT" if fast_dec.status == RecommendationStatus.PROMISING else "OPPOSE" if fast_dec.status == RecommendationStatus.NOT_RECOMMENDED else "UNCERTAIN"

    results.append({
        "path": "Fast Evaluator (run_50_case_post_clinicaltrials_fast)",
        "prediction": fast_pred,
        "recommendation_status": fast_dec.status.value,
        "opposition_score": opp_assess.score,
        "approved_indication_detected": fast_is_anchor,
        "decision_rule": fast_dec.deciding_rule.split(":")[0].strip(),
        "matched_term": matched_term_fast,
    })

    # 3. Benchmark Evaluator Path (BenchmarkRunner mapping)
    bench_class = map_recommendation_to_class(prod_rec["recommendation"])
    bench_pred = "SUPPORT" if bench_class == BenchmarkClass.POSITIVE else "OPPOSE" if bench_class == BenchmarkClass.NEGATIVE else "UNCERTAIN"
    results.append({
        "path": "Benchmark Evaluator (benchmark_runner)",
        "prediction": bench_pred,
        "recommendation_status": prod_rec["recommendation"],
        "opposition_score": prod_rec["opposition_score"],
        "approved_indication_detected": prod_is_anchor,
        "decision_rule": dec_rule_prod,
        "matched_term": matched_term_prod,
    })

    # 4. Targeted Evaluator Path (audit_p0b2_1_targeted / test_semantic_opposition_qualification)
    targ_dec = apply_decision_rules(
        is_approved=fast_is_anchor,
        matched_chembl_term=matched_term_fast,
        support_score=float(prod_rec.get("support_score", 0.0)),
        mechanistic_score=float(prod_rec.get("mechanistic_score", 0.0)),
        risk_score=float(prod_rec.get("risk_score", 0.0)),
        opp_assessment=opp_assess,
    )
    targ_pred = "SUPPORT" if targ_dec.status == RecommendationStatus.PROMISING else "OPPOSE" if targ_dec.status == RecommendationStatus.NOT_RECOMMENDED else "UNCERTAIN"
    results.append({
        "path": "Targeted Evaluator (canonical rules without override)",
        "prediction": targ_pred,
        "recommendation_status": targ_dec.status.value,
        "opposition_score": opp_assess.score,
        "approved_indication_detected": fast_is_anchor,
        "decision_rule": targ_dec.deciding_rule.split(":")[0].strip(),
        "matched_term": matched_term_fast,
    })

    return results

if __name__ == "__main__":
    results = run_tc062_through_all_evaluation_paths()
    print(f"{'Path':<45} | {'Pred':<8} | {'Status':<10} | {'Opp':<5} | {'Anchor':<7} | {'Rule':<10} | {'Term'}")
    print("-" * 120)
    for r in results:
        print(f"{r['path']:<45} | {r['prediction']:<8} | {r['recommendation_status']:<10} | {r['opposition_score']:<5} | {str(r['approved_indication_detected']):<7} | {r['decision_rule']:<10} | {r['matched_term']}")

    expected = ("SUPPORT", "PROMISING", 0.0, True)
    for r in results:
        actual = (r["prediction"], r["recommendation_status"], r["opposition_score"], r["approved_indication_detected"])
        assert actual == expected, f"Mismatch on {r['path']}: {actual} != {expected}"

    deciding_rules = {r["decision_rule"] for r in results}
    print(f"\nDeciding rules across all paths: {deciding_rules}")
    assert len(deciding_rules) == 1, f"Multiple deciding rules: {deciding_rules}"
    print("ALL 4 EVALUATION PATHS HAVE 100% PERFECT PARITY!")
